name: Deploy v3 Vault Subgraphs
on:
  push:
    branches: main
    paths:
      - "subgraphs/v3-vault/**"
  workflow_dispatch:

jobs:
  deploy-mainnet:
    uses: ./.github/workflows/deploy-subgraph.yml
    with:
      working-directory: subgraphs/v3-vault
      subgraph-name: balancer-v3
      manifest-file: subgraph.yaml
    secrets:
      GRAPH_DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}
  
  deploy-gnosis:
    uses: ./.github/workflows/deploy-subgraph.yml
    with:
      working-directory: subgraphs/v3-vault
      subgraph-name: balancer-v3-gnosis
      manifest-file: subgraph.gnosis.yaml
    secrets:
      GRAPH_DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}

  deploy-sepolia:
    uses: ./.github/workflows/deploy-subgraph.yml
    with:
      working-directory: subgraphs/v3-vault
      subgraph-name: balancer-v3-sepolia
      manifest-file: subgraph.sepolia.yaml
    secrets:
      GRAPH_DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}

  deploy-arbitrum:
    uses: ./.github/workflows/deploy-subgraph.yml
    with:
      working-directory: subgraphs/v3-vault
      subgraph-name: balancer-v3-arbitrum
      manifest-file: subgraph.arbitrum-one.yaml
    secrets:
      GRAPH_DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}
  
  deploy-base:
    uses: ./.github/workflows/deploy-subgraph.yml
    with:
      working-directory: subgraphs/v3-vault
      subgraph-name: balancer-v3-base
      manifest-file: subgraph.base.yaml
    secrets:
      GRAPH_DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}

  deploy-sonic:
    uses: ./.github/workflows/deploy-subgraph.yml
    with:
      working-directory: subgraphs/v3-vault
      subgraph-name: balancer-v3-sonic
      manifest-file: subgraph.sonic.yaml
    secrets:
      GRAPH_DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}

  deploy-avalanche:
    uses: ./.github/workflows/deploy-subgraph.yml
    with:
      working-directory: subgraphs/v3-vault
      subgraph-name: balancer-v3-avalanche
      manifest-file: subgraph.avalanche.yaml
    secrets:
      GRAPH_DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}

  deploy-optimism:
    uses: ./.github/workflows/deploy-subgraph.yml
    with:
      working-directory: subgraphs/v3-vault
      subgraph-name: balancer-v3-optimism
      manifest-file: subgraph.optimism.yaml
    secrets:
      GRAPH_DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}

  deploy-moksha:
    uses: ./.github/workflows/deploy-subgraph.yml
    with:
      working-directory: subgraphs/v3-vault
      subgraph-name: balancer-v3-moksha
      manifest-file: subgraph.moksha.yaml
    secrets:
      GRAPH_DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}